version: "3.7"

services:
  app:
    build: app
    container_name: django-gunicorn
    restart: always
    env_file:
      - django.env
    volumes:
      - type: bind
        source: ./app
        target: /src     
    ports:
      - "8000:8000"
    command:
      "gunicorn --reload --workers=2 --bind=0.0.0.0:8000 mysite.wsgi:application"
  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
